### ISSUE TITLE
MPV player and FFmpeg don't work on my old Sandy Bridge cpu

### ISSUE THREAD

**Issue by ZenKiyoshi** [MartinEesmaa/VVCEasy#16]
I try MPV and FFmpeg on AMD R5 3600 system, and they work perfectly.

But on my old Sandy Bridge system, they show error message.
![mpv-easy error](https://user-images.githubusercontent.com/98955073/177043633-72fa2888-ffdf-4c58-bfe0-43482b892dcf.png)

It's i5 2500S cpu. 

Both system run Window 10.

**Comment by MartinEesmaa** [comment]
@ZenKiyoshi, thanks for your reply!

I'm claiming that you ran perfect of MPV and FFmpeg on your AMD processor, I have same perfect work with my AMD R7 5800H.
But on your old computer of Intel CPU, it did not work.

I noticed that Intel CPU users cannot run on MPV/FFmpeg vvc build, because I used MinGW to compile FFmpeg and MPV too with my AMD processor, but I don't have an Intel laptop :(.

So I might use cross compilation on Windows in Linux, but my cross compilation is failed and it doesn't build for compile reason, see my GitHub actions of my self-hosted server: https://github.com/MartinEesmaa/mpv-vvc/runs/7154237122?check_suite_focus=true

Error:
```
sh: 1: x86_64-w64-mingw32-gcc -E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT libavdevice/avdeviceres.o: not found
CC	libavformat/aadec.o
x86_64-w64-mingw32-windres: preprocessing failed.
make: *** [/home/martineesmaa/actions-runner/_work/mpv-vvc/mpv-vvc/ffmpeg/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

I might try again and try to learn cross compilation of Windows in Linux...

- Martin Eesmaa

**Comment by ZenKiyoshi** [comment]
My old Sandy Bridge system can use FFmpeg (latest, gyan.dev)
![ffmpeg](https://user-images.githubusercontent.com/98955073/179184578-711cef88-907b-4802-b171-1768fdcce5ba.png)

**Comment by MartinEesmaa** [comment]
@ZenKiyoshi, I made static build of FFmpeg VVC build, but two DLL required to run executable files.

I tested this build with my AMD processor, works fine. For Intel CPU, I haven't tested and don't have it.

Link: https://mega.nz/file/T982HBpb#Gx1A75XPzSLsuvyq7ZSj9WULBDmm1UdGnyox-JjfmD4

- Martin Eesmaa

**Comment by ZenKiyoshi** [comment]
> @ZenKiyoshi, I made static build of FFmpeg VVC build, but two DLL required to run executable files.
> 
> I tested this build with my AMD processor, works fine. For Intel CPU, I haven't tested and don't have it.
> 
> Link: https://mega.nz/file/T982HBpb#Gx1A75XPzSLsuvyq7ZSj9WULBDmm1UdGnyox-JjfmD4
> 
> * Martin Eesmaa

The new build seem good, my Sandy Bridge cpu run fine, both encode and decode. (also AMD system)
![vvceasy-ffmpeg](https://user-images.githubusercontent.com/98955073/179336358-9334479b-0394-4bde-a097-1beeee9f4a99.png)
![vvceasy-ffplay](https://user-images.githubusercontent.com/98955073/179336359-1bb79a56-31eb-4966-9a43-65b5d9253dfc.png)

**Comment by MartinEesmaa** [comment]
@ZenKiyoshi, thanks for checking with my new static build of FFmpeg VVC version. I'll release the version and make important note for older builds of FFmpeg VVC, that it needs to be updated, so now Intel users can run well. MPV build will come soon later during my vacation.

**Comment by MartinEesmaa** [comment]
And MPV is now last to go.... and it should be complete.

**Comment by MartinEesmaa** [comment]
@ZenKiyoshi good news, FFmpeg VVC version and MPV VVC version is now fixed and updated versions. Can you confirm does MPV player VVC version work on your Intel Sandy Bridge?

- Martin Eesmaa

**Comment by ZenKiyoshi** [comment]
Missing postproc-55.dll, happens both Intel and AMD.
![vvceasy-mpv-error](https://user-images.githubusercontent.com/98955073/179383190-cfe9b66f-3e1d-4d8c-91ed-480fd30d0467.png)

**Comment by MartinEesmaa** [comment]
Sorry, I thought worked on my computer of Windows 11, here is a fix again:

https://mega.nz/file/KhlSzbBQ#uhyFwOPKFrssHweqXozS7B8iZxWtf0oX2o_jrY__rhQ

and I forgot to enable gnutls on ffmpeg shared before mpv build.

```
postproc-55.dll => /mingw64/bin/postproc-55.dll (0x7ffc01750000)
```

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
@ZenKiyoshi, here is my proof screenshot:

![proofofwindows10newmpv](https://user-images.githubusercontent.com/88035011/179384952-7194a4f6-3281-43c9-adc3-eb54fa1e6e26.png)

- Martin Eesmaa

**Comment by ZenKiyoshi** [comment]
it works finally.

![vvceasy-mpv](https://user-images.githubusercontent.com/98955073/179385437-8f59fccf-1205-400b-bc67-6d96ada5707c.png)

**Comment by MartinEesmaa** [comment]
Nice, @ZenKiyoshi! Thanks for finding the bug! :)

Have a nice day!

- Martin Eesmaa
