### ISSUE TITLE
AAC Support

### ISSUE THREAD

**Issue by baxxtor** [MartinEesmaa/VVCEasy#18]
Are ffmpeg_easy and ffplay_easy binaries available for download with AAC support?  If not, is there a way to build ffmpeg_easy and ffplay_easy with AAC support?

Any help would be appreciated.

**Comment by baxxtor** [comment]
I found a work around.   I converted the aac file to .m4a using ffmpeg.   I then used mp4box to merge the vvc and m4a aac audio and it worked.

**Comment by MartinEesmaa** [comment]
> I found a work around. I converted the aac file to .m4a using ffmpeg.
Did you convert to normal AAC codec with FFmpeg, but not xHE-AAC?

Note: Sorry, I forgot to build ffmpeg vvc, including xhe-aac decode only of build.

- Martin Eesmaa

**Comment by baxxtor** [comment]
Hi Martin,

Excellent point.  I converted from xHE-AAC to normal AAC without realizing
it which fixed the problem.  Would you be able to post a FFMPEG easyvvc
with xHE-AAC support.  I would really appreciate it.

Thanks

**Comment by NoUserNameForYou** [comment]
> 

And MPV (both linux and windows) too?

**Comment by MartinEesmaa** [comment]
> And MPV with xheaac and VVC (both linux and windows) too?

Windows is already done, but Linux there's a lot of distros.

I try to build static without mess DLL.

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
@baxxtor & @NoUserNameForYou 
See the static build problem issue: https://github.com/fraunhoferhhi/vvdec/issues/107#issuecomment-1217735276

I try to build static vvdec with MinGW, but FFmpeg does not recognize only static build.

- Martin Eesmaa

**Comment by baxxtor** [comment]
If possible, I would really appreciate it.

Thank You!

**Comment by MartinEesmaa** [comment]
@baxxtor & @NoUserNameForYou,

The FFmpeg complete static of vvc and xHE-AAC is here:
https://github.com/MartinEesmaa/VVCEasy/commit/c102e8923bc1ef12fa85315a92ee2c2682a2b1dc

- Martin Eesmaa

**Comment by NoUserNameForYou** [comment]
Thanks mate but I don't understand what that page is. Care to share bin files of mpv?

**Comment by NoUserNameForYou** [comment]
> @baxxtor & @NoUserNameForYou,
> 
> The FFmpeg complete static of vvc and xHE-AAC is here: [c102e89](https://github.com/MartinEesmaa/VVCEasy/commit/c102e8923bc1ef12fa85315a92ee2c2682a2b1dc)
> 
>     * Martin Eesmaa

Okay got the mega file but it's just FFmpeg. Can you please build an MPV for ubuntu and windows that can decode xheaac and vvc in mp4? Please :)

**Comment by DisaKzionda** [comment]
> > @baxxtor & @NoUserNameForYou,
> > The FFmpeg complete static of vvc and xHE-AAC is here: [c102e89](https://github.com/MartinEesmaa/VVCEasy/commit/c102e8923bc1ef12fa85315a92ee2c2682a2b1dc)
> > ```
> > * Martin Eesmaa
> > ```
> 
> Okay got the mega file but it's just FFmpeg. Can you please build an MPV for ubuntu and windows that can decode xheaac and vvc in mp4? Please if it's not too much work for you? :)

https://github.com/MartinEesmaa/VVCEasy/commit/fb3e9a1f0b273bda0e92c9015307306aa17e2e9c

**Comment by MartinEesmaa** [comment]
@baxxtor & @NoUserNameForYou, I have two problems on FFmpeg and MPV of Linux build only.

1. After building FFmpeg, I tried to playback vvc files on ffplay and gave me result segmentation fault. Only FFmpeg and FFprobe worked for encode/decode VVC files successfully.
2. I tried build MPV with `--enable-static-build` on my WSL, during linking to mpv, ld have problems no file found for reason. I tried to install Ubuntu packages and build packages and did not work everything, example:
```
/usr/bin/ld: cannot find -lgraphite2: No such file or directory
collect2: error: ld returned 1 exit status
```

Only one thing is do to put all required mpv build shared libraries (.so) into AppImage, so it can run any Linux distros. I haven't learn to make AppImage for myself, so it might be later until my update notice.

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
Dear @baxxtor and @NoUserNameForYou. I finally finished Linux MPV VVCEasy x64 build with AppImage.
https://github.com/MartinEesmaa/VVCEasy/commit/d3b38144af98041322301b6691f39ac159dc2183

- Martin Eesmaa

**Comment by NoUserNameForYou** [comment]
Thank you so much!

**Comment by MartinEesmaa** [comment]
You're welcome. @NoUserNameForYou! :)

I'll close the issue, because my MPV Linux static build request is finished.

- Martin Eesmaa
