### ISSUE TITLE
Wont work on Windows N

### ISSUE THREAD

**Issue by vaguiners** [MartinEesmaa/VVCEasy#22]
This ffmpeg build needs media feature pack.

**Comment by MartinEesmaa** [comment]
> This ffmpeg build needs media feature pack.

@vaguiners,
I think it maybe requires media feature pack for my FFmpeg custom build.
I haven't tested for Windows N edition. Can you test original FFmpeg build of gyan.dev or Btbn for Windows N?

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
Thank you, @vaguiners, for finding the error.
It seems one problem with my only custom FFmpeg build. 
I will add FFmpeg commit to my FFmpeg repository to fix Windows N version.

Actual behaviour of my FFmpeg custom build before patch:

![mfplaterrorofwindowsnversion](https://user-images.githubusercontent.com/88035011/206150602-1b27e78f-cba1-4cbd-b1d5-9c9b083806ad.png)

I'm going to patch these two FFmpeg's original patches to my FFmpeg repository:
https://github.com/FFmpeg/FFmpeg/commit/9fba0b8a8c754a012fc74c90ffb7c26a56be8ca0
https://github.com/FFmpeg/FFmpeg/commit/1cb601ad10313981209a5918fc36a968068fc0ec

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
I fixed my custom FFmpeg build for official patches, but my minor code changes to fix compilation errors:
https://github.com/MartinEesmaa/FFmpeg-FixVVC/commit/3f03861897eade74f49aea552fa4ba563a8f9076

It will take a couple of minutes to compile my windows FFmpeg custom build...

- Martin Eesmaa
