### ISSUE TITLE
can you add bdmv/dvd menu support. And yt-dlp support in mpv-android

### ISSUE THREAD

**Issue by aicynide** [MartinEesmaa/VVCEasy#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MartinEesmaa** [comment]
Hello @aicynide, I added yt-dlp, DVD and Blu-ray support into my mpv repository:
https://github.com/MartinEesmaa/mpv-android-vvc/commit/0d95b8bab453594cd205fc7dc27840ba74b78761
https://github.com/MartinEesmaa/mpv-android-vvc/commit/16da2e8e0404e915f930d6f6a58c93bc49e5cbdb

I will build soon as possible for new mpv android with new additional features that you requested.

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
@aicynide, finished. :)
https://github.com/MartinEesmaa/VVCEasy/commit/0e673ecabff01c095e5d326872b1f6806f8fe821
- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
Update: Sorry, I revert build back and this was crashed by libbluray and yt-dlp permission denied error 13. :(
- Martin Eesmaa

**Comment by aicynide** [comment]
Actually linux/windows mpv also doesn't support bluray menu

**Comment by aicynide** [comment]
Please add bluray/dvd menu support in mpv. Only yt-dlp support is enough in mpv-android

**Comment by aicynide** [comment]
@MartinEesmaa Please give mpv-android apk with yt-dlp support

**Comment by aicynide** [comment]
Do you think you would be able to add bluray menu support in mpv?

**Comment by aicynide** [comment]
@MartinEesmaa please build mpv-android with yt-dlp only

**Comment by MartinEesmaa** [comment]
Hello @aicynide, it seems my device has permission denied to install yt-dlp in my custom build, but here is apk arm64 to test your device: https://mega.nz/file/7l900ZwS#iEfCbHCYNX_BwdDbeqSX_StVjHEyXeJqGejHeRZeph8

Universal architecture of x86, x86_64, arm64 and armeabi: https://mega.nz/file/3lNgEQAA#h1sxEYUvzS1E6cZLrJd3SpSeXDZZDEMqdSXQFsEuyas

If your device says permission denied, it may be custom build error than original build. I may ask to solve permission denied error 13 :/.

- Martin Eesmaa

**Comment by aicynide** [comment]
I'm also getting permission error

**Comment by MartinEesmaa** [comment]
> I'm also getting permission error

Yeah you're right. Same as well too for my device. I guess I will ask why my custom build gets permission error for some reason to mpv community for yt-dlp. :/

**Comment by MartinEesmaa** [comment]
I decided to close the issue for some reasons that did not work my custom builds for Blu-ray and DVD menu on MPV Desktop and yt-dlp on MPV Android. Sorry, I tried to add your request features to my custom build, but did not work. 

Feel free to reopen the issue anytime.

Regards
- Martin Eesmaa
