### ISSUE TITLE
Do not display pict_Type  

### ISSUE THREAD

**Issue by he852100** [MartinEesmaa/VVCEasy#30]
Do not display pict_Type   
```
ffprobe_vvceasy.exe -hide_banner -loglevel error -select_streams V -threads 12 -print_format json -show_entries frame=pict_type,pkt_pts_time,best_effort_timestamp_time,pkt_size "$path 
```
        {
            "pkt_pts_time": "8.333333",
            "best_effort_timestamp_time": "8.333333",
            "pkt_size": "35",
            "pict_type": "?"
        },
        {
            "pkt_pts_time": "8.350000",
            "best_effort_timestamp_time": "8.350000",
            "pkt_size": "35",
            "pict_type": "?"
        },
        {
            "pkt_pts_time": "8.366667",
            "best_effort_timestamp_time": "8.366667",
            "pkt_size": "37",
            "pict_type": "?"
        },
        {
            "pkt_pts_time": "8.383333",
            "best_effort_timestamp_time": "8.383333",
            "pkt_size": "38",
            "pict_type": "?"
        },

**Comment by MartinEesmaa** [comment]
Hello, @he852100!

Maybe remove simple command called ***pict_type*** of show entries?
```
ffprobe_vvceasy.exe -hide_banner -loglevel error -select_streams V -threads 12 -print_format json -show_entries frame=pkt_pts_time,best_effort_timestamp_time,pkt_size "$path
```

- Martin Eesmaa
