### ISSUE TITLE
LAV Filters Compatibility Improvement Request

### ISSUE THREAD

**Issue by Hackjjang** [MartinEesmaa/VVCEasy#35]
DirectShow-based players other than MPC-HC... It doesn't even work with MPC-BE, etc.

We'd like to be able to play it on MPC-BE and since we've updated to LAV Filters 0.78, we'd like that to be handled as well.

https://github.com/clsid2/LAVFilters/commits/master
I hope this adds everything.

**Comment by MartinEesmaa** [comment]
Hi, @Hackjjang!

Thanks you for showing to me for his improvement commits. I merged to my repository and built it with improved.
Commit:
https://github.com/MartinEesmaa/VVCEasy/commit/0069e4cbb89c9ad6020a1d95e8d3f4a780f8ec28

I'll close the issue after the improvement build of LAVFilters is done.

If you have any questions or issues, feel free to reply me or/and reopen the issue again.
Thank you! :)

Regards
- Martin Eesmaa
