### ISSUE TITLE
FFmpeg VVENC version cannot use more threads

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#36]
Hello Martin, the CPU of my computer is AMD Ryzen 9 7945HX and the operating system is Windows11 23H2.

It only seems to support a maximum of 8 threads, but FFmpeg shows a maximum of 16 threads, and I'm not sure whether 8 or 16 processes are used.

My computer supports up to 32 processes, how can I maximize its use?

In addition, the Two-pass function cannot be used normally. Do I have to give up this version?
<img width="867" alt="屏幕截图 2023-12-24 1808" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/fb514028-52ce-47cf-abc6-c5a5109140cf">
<img width="867" alt="屏幕截图 2023-12-24 183911" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/482caea1-5e50-4a91-9c78-cd3cd1beb2cd">
<img width="932" alt="屏幕截图 2023-12-24 184347" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/2fc17ba0-c7ad-404a-a09f-074a277265b2">

**Comment by MartinEesmaa** [comment]
Hi, @jiangzemin-xudamin!

Thank you for providing your photos for the issue.

On third image, you used command to encode: `.\ffmpeg_vvceasy -threads 32 -i 1.mp4 -c:v libvvenc -preset 4 -b:v 3760k -c:a libopus -b:a 64k 2.mp4`, but it was wrong swap command.

The first thing is input goes first before you use threads command, not threads goes first before input.
Here's quick fix command:

```
.\ffmpeg_vvceasy -i 1.mp4 -threads 32 -c:v libvvenc -preset 4 -b:v 3760k -c:a libopus -b:a 64k 2.mp4
```

If you want to use two pass, you need to encode first pass before second pass command:
The first pass will use to create stats.json file on your located folder for only video. This will skip audio by using `-an`.
The second pass will read stats.json file, changing from pass 1 to 2 and you can encode audio too.

I added vvenc params command to make two pass correct.
```
.\ffmpeg_vvceasy -i 1.mp4 -threads 32 -c:v libvvenc -preset 4 -b:v 3760k -an -vvenc-params passes=2:pass=1:rcstatsfile=stats.json -f null NUL
.\ffmpeg_vvceasy -i 1.mp4 -threads 32 -c:v libvvenc -preset 4 -b:v 3760k -vvenc-params passes=2:pass=2:rcstatsfile=stats.json -c:a libopus -b:a 64k 2.mp4
```

You can find out more information about two passes: https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#rate-control-vbr-mode.

If you have any question or issue, feel free to reply me. :)
Thank you! :)

Regards
- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Thank you very much for your correction! Martin.
I rarely use the command line and make stupid mistakes.

**Comment by MartinEesmaa** [comment]
Hi, @jiangzemin-xudamin!
You're welcome and it's okay if you make a mistake. 
Also wishing you and everyone for Merry Christmas and Happy New Year!

- Martin Eesmaa
