### ISSUE TITLE
Can I use VVENC to compress photos?

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#39]
We know that HEVC can be used to compress images, usually with a ".heif" extension.

AV1 also supports image compression, usually with a ".avif" extension.

What about VVC? ".vif" or ".vvif" or ".266"?

In principle, VVC also compresses single-frame images, but no one seems to have developed an extension.

**Comment by MartinEesmaa** [comment]
Hello, @jiangzemin-xudamin!

Yes, you can use compress photo using vvenc for one frame only.
About .vif or .vvif is an unofficial VVC format, but I'm not sure and it still works. Official VVC formats used common raw bitstreams by .266, .vvc and .h266.

> In principle, VVC also compresses single-frame images, but no one seems to have developed an extension.

Yeah, I don't know, if no one may developed extension only like .vif and .vvif.

Thank you!
Feel free to reply me if you like! :)

- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Thank you very much for your answer.
