### ISSUE TITLE
Unable to convert PNG format photos to VVC format

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#45]
In the version of FFmpeg you modified, it is normal to convert photos in png format directly to avif or jxl, but it is not possible to convert them directly to vvc format. What parameters need to be added to convert properly?
<img width="1280" alt="屏幕截图 2024-04-05 175531" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/0a9e9be0-afe6-4b7a-b603-78aba7f9994e">
<img width="1166" alt="屏幕截图 2024-04-05 175801" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/0b2e4d17-0c44-4623-9e14-c663d41325d1">
<img width="1166" alt="屏幕截图 2024-04-05 175905" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/a4f81e45-e575-4e2b-80eb-74fb872128c4">

**Comment by MartinEesmaa** [comment]
Hello, @jiangzemin-xudamin!

When encoding lossless picture to VVC in FFmpeg, it has to be **divisible by 2** and only allows ***even numbers of integer***.
JPEG, AVIF, JPEG-XL and any supported images codecs can support any sizes of images without limitation.

I saw both errors output in your PowerShell terminal inside vvenc on FFmpeg:
```
Parameter Check Error: picture width is not an integer multiple of the specified chroma subsampling
Parameter Check Error: picture height is not an integer multiple of the specified chroma subsampling
```

The solution you can upscale or downscale using `-s:v` command to make sure it is divided by 2 on FFmpeg to avoid errors.

Here's the command:
```
.\ffmpeg_vvceasy -i 1.png -s:v 1894x1358 1.vvc
```

I hope this solves your problem. :)
Feel free to reply or ask question to me.

Thanks!

Regards
- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Think you very much! Martin

**Comment by jiangzemin-xudamin** [comment]
<img width="424" alt="屏幕截图 2024-04-06 084947" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/ea7095d2-e00b-4b94-a8e0-72f694429917">
With the default parameters, the VVC file is the one that takes up the least disk space among them
