### ISSUE TITLE
I tried to convert 16K videos! It was just too much of a RAM hog!

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#48]
Today, I tried to use FFmpeg-VVENC to convert 15360*8640 resolution video, and then my computer got stuck in an inoperable state. So I went into Windows 11's safe mode and was finally able to compress it!
In order to have a smooth conversion, I first converted this video to YUV444P format to avoid consuming more RAM.

What means can I use to reduce the RAM consumption while keeping the capacity of the video compression intact?

![IMG_20240527_154349831_HDR](https://github.com/MartinEesmaa/VVCEasy/assets/55375989/3071c1ae-fb28-4e51-8ec9-01759aa6a30d)

What the hell is this Microsoft?Windows11 safe mode state can not use the screenshot function.

![屏幕截图 2024-05-27 162551](https://github.com/MartinEesmaa/VVCEasy/assets/55375989/7b68cb77-1542-40f0-b66a-068b44da6056)

Fortunately, the conversion has been successful

**Comment by jiangzemin-xudamin** [comment]
Even though I know that 16k resolution is too early, and compressing 16k video is just an experiment, there are times when it's fun to "fiddle" with it.

**Comment by MartinEesmaa** [comment]
Hello, @jiangzemin-xudamin. Thank you for providing more information to me!

> What means can I use to reduce the RAM consumption while keeping the capacity of the video compression intact?

Encoding to 16k VVC might be hard which could slow down for low-end and average gaming computers, which maybe requires high-end computers for example like 128GB Memory RAM, your memory is 32 GB. 

Computers uses more powerful than laptops, which computer users can upgrade motherboard, CPU, GPU and more, but for laptop upgrade, it may be possible or not possible to upgrade CPU, memory is upgradable and okay, but you have to look what it supports maximum memory ram size on your laptop...

If you would like to reduce memory on Windows, you can use System Informer or Process Explorer.

For System Informer or Process Explorer, right click of executable file point from your mouse and you can see I/O Priority (for System Informer) and Priority (for both programs) and select low.

> What the hell is this Microsoft?Windows11 safe mode state can not use the screenshot function.

Hmm, that's weird, but have you tried with Windows button + Print screen button, Print Button to Paint, Snipping tool...

> Maybe I should try another operating system?

Well, you can use Linux to reduce memory usage by not using Windows normal/bloated version or alternatively you can debloat Windows by your own installation like AtlasOS or ReviOS.

> Even though I know that 16k resolution is too early, and compressing 16k video is just an experiment, there are times when it's fun to "fiddle" with it.

Well encoding much resolutions will become much slower for taking too long with little frozen on little high-end laptop.

Any question or issue, let me know. Thanks! :)

Regards
- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
>Hmm, that's weird, but have you tried with Windows button + Print screen button, Print Button to Paint, Snipping tool...

@MartinEesmaa. Yes, I have tried them all, it may be a bug in the current version of Windows 11, but not in the old Windows 11 version.

**Comment by MartinEesmaa** [comment]
> Yes, I have tried them all, it may be a bug in the current version of Windows 11, but not in the old Windows 11 version.

It could be likely bug when you're running current version of Windows 11 trying to take screenshot than old version is fine.
You can try update latest like 24H2, restart again or you can run and scan file corruptions if both first did not work:

```
sfc /scannow
```

If Windows SFC tool found corrupted files and successfully repaired, you can try again to take screenshot or restart again.
If not found corrupted... it may be bug or disabled screenshotting on safe mode of your current Windows 11 version :/.

- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
>Well, you can use Linux to reduce memory usage by not using Windows normal/bloated version or alternatively you can debloat Windows by your own installation like AtlasOS or ReviOS.

Thank you for introducing these two third-party modified versions of Windows systems. I will try them when I have time in the future.

**Comment by jiangzemin-xudamin** [comment]
>Computers uses more powerful than laptops, which computer users can upgrade motherboard, CPU, GPU and more, but for laptop upgrade, it may be possible or not possible to upgrade CPU, memory is upgradable and okay, but you have to look what it supports maximum memory ram size on your laptop...

As far as I know, in recent years, laptops support up to 96GB RAM, and only desktops can support 128GB or more. But my AMD Ryzen™ 9 7945HX supports up to 64GB.
https://www.amd.com/en/products/processors/laptop/ryzen/7000-series/amd-ryzen-9-7945hx.html
