### ISSUE TITLE
[[BUG]]Your recent builds of FFmpeg VVCEasy have bug

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#49]
**Describe the bug**
>05/06/2024: Updated FFmpeg with latest nightly, vvenc, vvdec and others.

Encoding vvenc does not work properly, it will abort and jump to the next line of command.

**To Reproduce**
`.\ffmpeg_vvceasy -i 1.mp4 -threads 32 -c:v libvvenc -preset 4 -b:v 0 -qp 35 -an -sn 2.mp4`

**Expected behavior**
Generates 1KB file and cannot be used

**Screenshots**
<img width="869" alt="屏幕截图 2024-06-06 024455" src="https://github.com/MartinEesmaa/VVCEasy/assets/55375989/a6dd3808-887b-468e-832c-440a2c88e13a">

**Desktop (please complete the following information):**
- Operating system: Windows 11
- Version: 23H2

**Comment by MartinEesmaa** [comment]
Hello, @jiangzemin-xudamin. Thank you for sharing screenshot! :)

> Encoding vvenc does not work properly, it will abort and jump to the next line of command.
> Generates 1KB file and cannot be used

Hmm, that's weird... :/. My current system works fine to encode of my latest FFmpeg custom build without issue for anything.
It is kinda bug of every my FFmpeg custom builds when encoding VVC, but your previous was fine.

If you can share your H.264 video file of 2 seconds (1.mp4) over to this issue on GitHub or you can send an email to me at martin.eesmaa@protonmail.com

It takes bit encoding time normally, but it starts current showing 0kib from beginning until approximately 10 seconds encoded will show 256kib result and so on until hits EOF (end of file) and process is completed.

When you encode to VVC, the vvenc encoding will start but it won't report KiB until every approximately 10 seconds encoded will show a bitrate KiB numbers without 0 KiB standing stuck.

Feel free to reply or ask question to me. Thanks! :)

Regards
- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
@MartinEesmaa. The problem only occurs if the original file is encoded in H.264, but H.265 is normal.

https://github.com/MartinEesmaa/VVCEasy/assets/55375989/32f3cbcf-1039-4ebe-9e2a-59a6b3f7fb87

**Comment by jiangzemin-xudamin** [comment]
@MartinEesmaa 
I know the reason. The new version does not support 32 threads. It can only be used normally after changing to 16 threads.

**Comment by MartinEesmaa** [comment]
Hi, @jiangzemin-xudamin. Thank you for knowing the reason! :)

I found the solution, the problem was multi threading profile was added recently to vvenc: https://github.com/fraunhoferhhi/vvenc/commit/77574c7a60f8dc2ecd9e92eb7fdae271718a8e50#diff-eeeda5c283ddd8c9998302e0601cee097a07327291af00636295f6415d38e7d2

```
--mtprofile [auto] enable automatic multi-threading setting (enables tiles, IFP and WPP automatically depending on the number of threads)
```

When you're using 32 threads without customizing mtprofile, it crashes. However to solve the problem, you need to add on FFmpeg:

```
-vvenc-params mtprofile=0
```

Complete example usage:

```
ffmpeg_vvceasy -i 1.mp4 -threads 32 -c:v libvvenc -preset 4 -vvenc-params mtprofile=0 -b:v 0 -qp 35 2.mp4
```

Any question or issue, feel free to let me know. Thanks! :)

Sincerely,
Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Thanks! :)
U R very good！！
