### ISSUE TITLE
Could you add information about the MPC-BE player?

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#50]
Starting with MPC-BE 1.7.0, support for VVC and USAC has been added.
https://github.com/Aleksoid1978/MPC-BE
It's time to ditch MPC-HC!

**Comment by MartinEesmaa** [comment]
Hello, @jiangzemin-xudamin! Thank you for giving the link.
I can claim that is officially added support of VVC and USAC starting since MPC Black Edition 1.7.0.
So I will add information to LAVFilters folder soon possible.

Thanks! :)

- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Thanks! :)
