### ISSUE TITLE
Can't start mpv-vvceasy.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by greenozon** [MartinEesmaa/VVCEasy#54]
Can't start mpv-vvceasy.exe

error:

```
---------------------------
mpv-vvceasy.exe - Entry Point Not Found
---------------------------
The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```

version tried:

![image](https://github.com/user-attachments/assets/ee834d8a-509b-42ee-9dd5-360057271df2)

**Comment by MartinEesmaa** [comment]
Hi, @greenozon! Thank you for your report.

That's weird that did not run my custom build when you running Windows 7. :/
Can you try vanilla [mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake/releases) still if it works? Sorry I haven't updated yet to my custom MPV build, will come later...

Note: My custom FFmpeg and MPV builds of desktop OS have available x86_64/arm64 architecture.

If not, try my custom FFmpeg builds and make sure it's installed Microsoft Visual C++ Redistributable too.
If still doesn't work, feel free let me know. :) Thanks!

- Martin Eesmaa

**Comment by greenozon** [comment]
Hi!
Here is a try of vanilla mpv builds:

---------------------------
mpv.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000005). Click OK to close the application. 
---------------------------
OK   
---------------------------

on 
mpv-x86_64-gcc-20240902-git-afdbbac.7z
mpv-x86_64-20240902-git-afdbbac.7z
mpv-i686-20240902-git-afdbbac.7z

is it end of life?
(same strange noname error for ffmpeg binaries)

**Comment by greenozon** [comment]
The older build from mega also produces this error:

```
---------------------------
mpv-vvceasy.exe - Entry Point Not Found
---------------------------
The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------

```

**Comment by MartinEesmaa** [comment]
Hey @greenozon. Thanks for report.

I think I found the problem, which vanilla mpv sets restricted minimum version to run Windows 10 :(.
https://github.com/mpv-player/mpv/blob/master/meson.build#L310

WINVER 0x0A00 is Windows 10, but your Windows 7 of WINVER is 0x0601.
Learn more: https://github.com/mpv-player/mpv/blob/master/meson.build#L310

I will patch the file soon as possible... Thank you! :)

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
I patched the file of my forked repository:
https://github.com/MartinEesmaa/mpv-winbuild-cmake/commit/13bdd163e5955c55aaf8ec36de52ad9425c56cda

I will test it out on my Windows 7 x64 virtual machine when it's completed, later...

- Martin Eesmaa

**Comment by greenozon** [comment]
Thanks for taking care of this (I believe minor) issue
but anyway - huge respect!

**Comment by MartinEesmaa** [comment]
No problem, @greenozon! :D

One thing I also revert old code for example this one to make compatible: https://github.com/mpv-player/mpv/commit/66c3110a856f11c1fc68044e6ef426991911aa25

Anyway, I have to go to bed soon, so I'll have look later for commits about Windows 7 changes of MPV vanilla repository, patching more and testing out to see if it works.

My second childhood of Windows 7 was good. :)

- Martin Eesmaa

**Comment by greenozon** [comment]
thanks
I promise to be a high quality and responsive tester :)

**Comment by MartinEesmaa** [comment]
Hi, @greenozon!

Unfortunately, it came different error code with 0xc0000005 on my Windows 7 x64 virtual machine. :(
![unfortunatelyerrorcameupmpv-vvceasy](https://github.com/user-attachments/assets/eaedb8fa-5450-49e7-a035-29f9fa76192c)

Tried with my patches about Windows 7, didn't work. You can look the failed patch: https://github.com/MartinEesmaa/mpv-winbuild-cmake/blob/0fd266a8431fcab3f1565124285adb545de13856/packages/mpv-vvceasy02.patch

Feel free to reply or ask question to me. Thanks!

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
I will contact MPV developers from IRC chat of my matrix account

So there are two options:
1. If you wanna continue to use MPV and to avoid 0xc0000005 error, I have to contact MPV. If not, Windows 7 support is down :(. I will try oldest build last one if works for an update edit.
2. You can use alternative media players of GUI friendly for example MPC-HC or MPC-BE on my forked LAVFilters: https://github.com/MartinEesmaa/VVCEasy/tree/master/LAVFilters

- Martin Eesmaa

**Comment by greenozon** [comment]
thanks for reply
do you have some clues how one might figure out what is the latest mpv version/tag/branch that does support W7?

2) I"m already using alternative players (MPC-HC I guess) but mpv looks more charming and geek :)

thanks, Martin

**Comment by greenozon** [comment]
BTW, I've tried mpv.net edition - but even more cryptc issue was shown:

![image](https://github.com/user-attachments/assets/8b2f8aaf-6ee4-4f50-a83e-4e42e4016713)

**Comment by MartinEesmaa** [comment]
Hey, @greenozon! Thanks for little detail and screenshot to me! :)

> do you have some clues how one might figure out what is the latest mpv version/tag/branch that does support W7?

I kinda don't know, but I found last Windows 7 version support working on MPV:

Commit of last working Windows 7 version: https://github.com/MartinEesmaa/VVCEasy/commit/50a922e6fac9277a22c76f87f7e5d51c73af6a9a

Last working of Windows 7 commit mpv-vanilla built on my custom build:
https://github.com/mpv-player/mpv/commit/1dd71a6093678080497ae4d79ef38589e4d6d67f

See my screenshot:
![lastwindows7workingmpv](https://github.com/user-attachments/assets/a9f515d1-1f18-4b88-942b-7cbd2ce77e28)

Maybe mpv dropped support or mpv-winbuild-cmake was it...? I'll might have look later... :/

- Martin Eesmaa

**Comment by greenozon** [comment]
Wow, looks super great
is it possible to get those bits compiled?

**Comment by MartinEesmaa** [comment]
Hi, @greenozon! Thank you!

> is it possible to get those bits compiled?

 Not sure about that... Do you mean video bits like 10 bits or the architecture?

- Martin Eesmaa

**Comment by greenozon** [comment]
sorry for cunfusion
I meant to have a build (latest one?) that allows to run on W7
placed somewhere...
(as you show some git refs and I did not find the compiled code for those old chnages)

**Comment by MartinEesmaa** [comment]
Hi, @greenozon!

That's okay for confusion. :)

> I meant to have a build (latest one?) that allows to run on W7
placed somewhere...

Actually, there's only one can run latest MPV build for your Windows 7: https://github.com/eko5624/mpv-win64
I haven't tested yet to run in Windows 7, I'll run later...

> (as you show some git refs and I did not find the compiled code for those old changes)

I kinda don't know, so like pre-compiled codes I showed links with commits :/

- Martin Eesmaa

**Comment by greenozon** [comment]
OK, thanks
lets stop this discussion as it does not make any sense
looks like people do not care on older stuff, I hope sometime someone will find build for windows 13 when there will be win20 on the street :)
