### ISSUE TITLE
I had to succumb to reality and switch to AV1 and HE-AAC V2.

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#55]
Recently, I intend to convert a large batch of video files about Jackie Chan's movie works, which are usually encapsulated in MKV format, and most of them contain multiple audio streams and subtitle streams per video file. So I encountered some problems ......
![PixPin_2024-10-06_13-28-59](https://github.com/user-attachments/assets/6415345c-e28a-44c2-afb1-68321a20a070)

First, to convert these videos, it is impractical to use VVENC encoder, which will result in a conversion time of more than 1 year! Switching to NVENC with AV1 support would be the best option instead.
Secondly, Exhale doesn't seem to support batch conversion of multiple audio streams in ffmpeg's pipe mode, which would result in an error. In addition, ffmpeg currently does not support xHE-AAC decoding perfectly, and audio with SBR cannot be used, which will lead to failure in converting other audio codecs! I had to switch to HE-AAC V2, but Gyan's license for compiling ffmpeg doesn't include the non-free option, and I couldn't find FDK-AAC on Gyan's official website, so I had to give up on the GYAN version.
Now, once again, I'm going to go with your modified FFMPEG because your version supports FDK-AAC!
Thirdly, MP4 files are not friendly to special subtitle format support, and mkv has not provided official support for VVC format so far, which is another reason for me to give up VVC.
Finally, for individual images or audio, I still retain the use of VVC and xHE-AAC.
```batchfile
md output

for %%a in (*.wav *.mp3 *.flac *.m4a *.aac *.amr *.ogg) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -vn -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\output\%%~na.m4a"
)
for %%a in (*.png *.jpg *.jpeg *.heif *.avif *.jxl *.gif *.bmp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -c:v libvvenc -preset 4 -vvenc-params mtprofile=0 -b:v 0 -qp 26 ".\output\%%~na.h266" 
)
for %%a in (*.mp4 *.webm *.mkv *.mov *.avi *.rm *.rmvb *.flv *.3gp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -map 0 -strict -2 -c:s copy -c:a libfdk_aac -profile:a aac_he_v2 -ac 2 -vbr 3 -c:v av1_nvenc -preset p7 -qp 104 ".\output\%%~na.mkv"
)

echo "!!!Conversion completed!!!"
pause

```

**Comment by jiangzemin-xudamin** [comment]
For individual audio files that have been converted to xHE-AAC encoding, I can do a batch format conversion directly through EZ CD Audio Converter.

**Comment by jiangzemin-xudamin** [comment]
Why I don't choose opus is because HE-AAC V2 still outperforms OPUS at the same bitrate, and it would be nice to batch convert audio streams to xHE-AAC.
https://www.youtube.com/shorts/f-_6XEmiGNc

**Comment by MartinEesmaa** [comment]
Hi, @jiangzemin-xudamin. Thanks for lot information gave to me! 💯 :)

> First, to convert these videos, it is impractical to use VVENC encoder, which will result in a conversion time of more than 1 year! Switching to NVENC with AV1 support would be the best option instead.

Claiming more than 1 year to encode VVC using vvenc with FFmpeg is take so long like insane. For next year or two years, I hope Intel, NVIDIA and AMD will release VVC Hardware Encoding of GPU if possible. Intel already supports VVC HW decoding for Lunar Lake. I have still AV1 encoding support of my NVIDIA RTX 4050 Laptop GPU.

> Secondly, Exhale doesn't seem to support batch conversion of multiple audio streams in ffmpeg's pipe mode, which would result in an error.

I kinda don't know for me, but I hope it only supports for single at one time when running one batch file at time. A tip is for you can run multiple batch files to convert faster on your Windows, you know like running multiple batch files with inserted specified video file name each or single batch file using argument type after batchfile.

> In addition, ffmpeg currently does not support xHE-AAC decoding perfectly, and audio with SBR cannot be used, which will lead to failure in converting other audio codecs! I had to switch to HE-AAC V2, but Gyan's license for compiling ffmpeg doesn't include the non-free option, and I couldn't find FDK-AAC on Gyan's official website, so I had to give up on the GYAN version. Now, once again, I'm going to go with your modified FFMPEG because your version supports FDK-AAC!

Well for vanilla/original FFmpeg has limited features of xHE-AAC decoding which may be missing SBR and other stuffs, but Fraunhofer FDK library decodes fine to play xHE-AAC audio files. Also when you're tried Gyan's FFmpeg build, it doesn't have fdk-aac which means the reason is Gyan doesn't want non-free access to avoid license incompatible violation problem.

Me and others supports FDK-AAC external feature to FFmpeg builds, including my custom build, but thanks for returning back to reuse my modified FFmpeg build, but others are still supporting FDK-AAC of their own builds. :)

> Thirdly, MP4 files are not friendly to special subtitle format support, and mkv has not provided official support for VVC format so far, which is another reason for me to give up VVC.
Finally, for individual images or audio, I still retain the use of VVC and xHE-AAC.

Well, I kinda agree which MP4 maybe not friendly to subtitle, but only friendly subtitle is Timed Text (tx3g).
Matroska is all friendly to include support subtitles.
For VVC matroska muxing, it's not completed yet to probably mux it on mine one, but official Matroska tag of `V_MPEGI/ISO/VVC` does.

You're welcome to encode single intra photo frame using VVC and for music using xHE-AAC by your own choice to make audio album encoded collections.

Feel free to reply or ask question to me. Thanks very much! :)

- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
@MartinEesmaa  Thanks for the answer, I've modified the batch file I wrote once again, this time treating the video files as “MKV” and “non-MKV”. Unfortunately, I failed to extract and convert one of the subtitle streams from the mkv file, but fortunately extracting the audio stream and converting it to xHE-AAC was successful.
For now, I can only process the original MKV video file in three steps:
1. Mask the audio stream first, convert the video stream and copy the subtitle stream.
2. Utilize exhale with pipeline mode to convert each channel audio stream separately.
3. Use MKVToolNix to merge the files generated in the first and second steps. 
```batchfile
md output

for %%a in (*.wav *.mp3 *.flac *.m4a *.aac *.amr *.ogg) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -vn -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\output\%%~na.m4a"
)
for %%a in (*.png *.jpg *.jpeg *.heif *.avif *.jxl *.gif *.bmp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -c:v libvvenc -preset 4 -vvenc-params mtprofile=0 -b:v 0 -qp 26 ".\output\%%~na.h266" 
)


md temp
for %%a in (*.mp4 *.webm *.mov *.avi *.rm *.rmvb *.flv *.3gp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -vn -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na.m4a"
)
for %%a in (*.mp4 *.webm *.mov *.avi *.rm *.rmvb *.flv *.3gp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -an -c:v av1_nvenc -preset p7 -qp 104 ".\temp\%%~na.webm"
)
for %%a in (.\temp\*.webm) do ( 
mp4box -add "%%~sa" -add ".\temp\%%~na.m4a" ".\output\%%~na.mp4"
)

for %%a in (*.mkv) do ( 
md ".\temp\%%~na"
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -map 0 -strict -2 -c:s copy -an -c:v av1_nvenc -preset p7 -qp 104 ".\temp\%%~na\0000.mkv"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:0 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\0.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:1 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\1.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:2 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\2.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:3 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\3.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:4 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\4.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:5 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\5.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:6 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\6.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:7 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\7.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:8 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\8.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:9 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\9.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:10 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\10.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:11 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\11.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:12 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\12.m4a"
)
echo Manually combine all audio streams using MKVToolNix.
pause
rmdir /s/q temp

echo "!!!Conversion completed!!!"
pause
```

**Comment by jiangzemin-xudamin** [comment]
![PixPin_2024-10-11_16-12-20](https://github.com/user-attachments/assets/85a76fa5-c397-4f3e-bf15-80dffaf90e31)

> For VVC matroska muxing, it's not completed yet to probably mux it on mine one, but official Matroska tag of V_MPEGI/ISO/VVC does.

Currently MKVToolNix doesn't support VVC, mkv files containing vvc mixed with this software can't be played by video players. But the good thing is that xhe-aac can be streamed as MKV files, although it is recognized as normal AAC by this software.

**Comment by MartinEesmaa** [comment]
Hi again, @jiangzemin-xudamin! Thanks for a little response! :)

> Currently MKVToolNix doesn't support VVC, mkv files containing vvc mixed with this software can't be played by video players. But the good thing is that xhe-aac can be streamed as MKV files, although it is recognized as normal AAC by this software.

Official MKVToolNix does not support VVC, so we have to wait little long time until someone makes a pull request for support VVC
Also you can look oficial Matroska specification about VVC: https://github.com/ietf-wg-cellar/matroska-specification/blob/master/codec_specs.md#v_mpegiisovvc

Some official video players can't play VVC mixed unrecognized, but MPV does have support: https://github.com/mpv-player/mpv/commit/4f828676fd5aa81ded1be596440ab7c978c48be7

Good thing mkvtoolnix can recognize xHE-AAC behaves normal AAC :).

Feel free to reply or ask me again. Thanks! :)

Sincerely,
Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
>A tip is for you can run multiple batch files to convert faster on your Windows, you know like running multiple batch files with inserted specified video file name each or single batch file using argument type after batchfile.

@MartinEesmaa .Hey!
I'm now trying to run 4 powershell programs to run the batch file, this time I'm reusing vvenc and removing the “-threads” from parts of the batch file. I've noticed a reduction in RAM usage (it was taking up 20GiB, now 14GiB) and it seems to be running a bit more efficiently, however, it's still very slow.
![PixPin_2024-10-12_14-17-18](https://github.com/user-attachments/assets/447cbfd8-d982-4236-b386-0816910793f0)
```batchfile
md output

for %%a in (*.wav *.mp3 *.flac *.m4a *.aac *.amr *.ogg) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -vn -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\output\%%~na.m4a"
)
for %%a in (*.png *.jpg *.jpeg *.heif *.avif *.jxl *.gif *.bmp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -c:v libvvenc -preset 4 -b:v 0 -qp 26 ".\output\%%~na.h266" 
)


md temp
for %%a in (*.mp4 *.webm *.mov *.avi *.rm *.rmvb *.flv *.3gp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -vn -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na.m4a"
)
for %%a in (*.mp4 *.webm *.mov *.avi *.rm *.rmvb *.flv *.3gp) do ( 
.\ffmpeg_vvceasy -i "%%~sa" -an -c:v libvvenc -preset 4 -b:v 0 -qp 26 ".\temp\%%~na.vvc"
)
for %%a in (.\temp\*.vvc) do ( 
mp4box -add "%%~sa" -add ".\temp\%%~na.m4a" ".\output\%%~na.mp4"
)

for %%a in (*.mkv) do ( 
md ".\temp\%%~na"
.\ffmpeg_vvceasy -i "%%~sa" -threads 32 -map 0 -strict -2 -c:s copy -an -c:v copy ".\temp\%%~na\0000.mkv"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:0 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\0.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:1 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\1.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:2 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\2.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:3 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\3.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:4 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\4.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:5 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\5.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:6 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\6.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:7 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\7.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:8 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\8.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:9 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\9.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:10 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\10.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:11 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\11.m4a"
.\ffmpeg_vvceasy -i "%%~sa" -map 0:a:12 -vn -sn -threads 32 -c:a pcm_s32le -strict -2 -ac 2 -f wav - | .\exhale b ".\temp\%%~na\12.m4a"
)
echo Manually combine all audio streams using MKVToolNix.
pause
for %%a in (*.mkv) do ( 
.\ffmpeg_vvceasy -i ".\temp\%%~na\0.mkv" -map 0 -c:s copy -c:a copy -c:v libvvenc -preset 4 -b:v 0 -qp 26 ".\output\%%~na.mkv" 
)
pause
rmdir /s/q temp

echo "!!!Conversion completed!!!"
pause

```

**Comment by jiangzemin-xudamin** [comment]
>Some official video players can't play VVC mixed unrecognized, but MPV does have support

It's a shame, I don't understand why other software has such limitations. MPV compatibility is really strong though!
